default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000

development:
  <<: *default
  host: db
  database: rails_react_redux_typescript_boilerplate_development

test:
  <<: *default
  host: db
  database: rails_react_redux_typescript_boilerplate_test

production:
  <<: *default
  database: rails_react_redux_typescript_boilerplate_production
